import { mkdir } from "node:fs/promises";
await mkdir("packages/sdk/src/generated", { recursive: true });
for (const name of [
  "WayleaveAgentRegistry",
  "AccountFactory",
  "OperatingAccount",
  "MockUSDC",
  "KernelAccountFactory",
  "NFTOwnerValidator",
  "PasskeyAccountFactory",
  "WebAuthnValidator",
  "AccountOwnedENSV2IdentityAdapter",
  "Kernel",
  "EntryPoint",
]) {
  const artifact = await Bun.file(`packages/contracts/out/${name}.sol/${name}.json`).json();
  const path = `packages/sdk/src/generated/${name}.ts`;
  const content = `// Generated by bun run abi. Do not edit.\nexport const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  if (!(await Bun.file(path).exists()) || (await Bun.file(path).text()) !== content)
    await Bun.write(path, content);
}
